### ISSUE TITLE
Keyvi compilation loses some records

### ISSUE THREAD

**Issue by DavidNemeskey** [cliqz-oss/keyvi#47] opened 2015-10-28 11:56 UTC
@hendrik-cliqz I have uploaded the file to s3.

**Comment by hendrik-cliqz** [comment] 2015-10-29 13:39
I checked the file, the problem are duplicated keys. sort|uniq does not work as values are different. But if I only take the keys ans uniq them, I get exactly the count that keyviinspector has.

**Comment by hendrik-cliqz** [comment] 2015-10-29 13:40
closing as by design. I will follow up to find out the origin of this data, it should not have these duplicates in the first place.

**Closed by hendrik-cliqz** 2015-10-29 13:40 UTC
